<%@page import="com.ibm.icu.text.SimpleDateFormat"%>
<%@page import="java.util.Date"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<html>
    <head>
<title>Add Article</title>
<script>
	function counter(msg) {
		document.getElementById('counter_div').innerHTML = msg.value.length;
	}
</script>
<meta charset="utf-8">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<style>
table,tr,td{

}
</style>

<body>
	
	<%@ include file="header1.jsp"%>
	
	<div class="container-fluid">
	<div class="row">
	<div class="col-md-2">
	</div>
	<div class="col-sm-9">
	<h2 style="margin-left:80px;margin-top:30px;">Start Writing Your Articles Here ...</h2>

	<form:form method="POST" action="save.html"
		commandName="article">
		
		<%if (request.getAttribute("error") != null) {%>
			Error:<%=request.getAttribute("error")%>
		<%}%>
		<table>
			<tr>
				<td><form:label class="form-group" path="id" >Category:</form:label></td>
				<td><select class="form-control" name="catname">
						<c:forEach items="${cats}" var="cat">
							<option value="${cat.name}">${cat.name}</option>
						</c:forEach>
				</select></td>
			</tr>
			<tr>
				<td><form:label path="id">ID:</form:label></td>
				<td><form:input class="form-control" path="id" value="${article.id}" readonly="true" placeholder="Autogenerated" /></td>
				<td><form:label style="margin-left:40px;" path="date" value="${article.date}"
						readonly="true" />Date:<%=new SimpleDateFormat("dd.MM.yy").format(new Date())%></td>

			</tr>
			<tr>
				<td><form:label path="title">Title:</form:label></td>
				<td><form:input class="form-control" path="title" required="required" placeholder="Input Appropriate Title" value="${article.title}" size="50" /></td>
				<td><div id="counter_div" align="left"></div></td>
			</tr>			
			<tr>
				<td></td>
				<td><form:textarea class="form-control" path="articletext" required="required"
						value="${article.articletext}" rows="13" cols="80"
						onkeyup="counter(this);"  /></td>

			</tr>
			<tr>
				<td></td>
				<td colspan="2"><input type="submit" style="margin-top:6px;margin-left:250px;" class="btn btn-outline-primary" value="Submit Article" /></td>
			</tr>

		</table>
	</form:form>
	</div>
	<div class="col-md-1">
	</div>
	</div>
	</div>
</body>
</html>