<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>ADD CATEGORIES</title>
<style>
#front{
    border-radius:10px;
    color:black;
}
#bottom
{ 
	background-color: #2e3b4f;
    border-radius:10px;
    color:white;
}

#border
{
	
	border:solid 1px white;
}
.fixed
{
position:fixed;
}


</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
<%@ include file="header1.jsp"%>
 
 <div class="container">
 <div class="row">
 <div class="col-md-4 fixed" style="margin-top:50px;" id="front">
 <table>
		<form:form method="POST" action="savecat.html">
			<h2>ADD CATEGORY:</h2>
			<tr>
				<td><form:label style="color:black" for="categoryid" path="id">Category ID:</form:label></td>
				<td><form:input class="form-control" path="id" value="${category.id}"
				 		readonly="true" placeholder="Autogenerated" /></td>
			</tr>
			<tr>
				<td><form:label style="color:black"  for="category" path="name">Category:</form:label></td>
				<td><form:input class="form-control" autocomplete="off" placeholder="Add Desired Category" path="name" value="${category.name}" /></td>
			</tr>
			<tr>
				<td colspan="2"><input type="submit" class="btn btn-outline-info" style="margin-left:10px;margin-top:10px;" value="Add" /></td>
			</tr>
	</form:form>
	</table>
 </div>
 <div class="col-md-4" style="margin-top:50px;">
 </div>
 <div class="col-md-4" style="margin-top:50px;" id="bottom">
 	<h2>Category List:</h2>
 	<c:if test="${!empty cats}">
		<table id="border" border="1" class="table table-striped">
		<thead>
			<tr>
				<th style="color:white;">Category ID</th>
				<th style="color:white;">Category Name</th>				
			</tr>
		</thead>
		<tbody>
			<c:forEach items="${cats}" var="cat">
				<tr>
					<td style="color:white;"><c:out  value="${cat.id}" /></td>
					<td style="color:white;"><c:out  value="${cat.name}" /></td>
				</tr>
			</c:forEach>
			</tbody>
		</table>
	</c:if> 
 </div>
 
 </div> 
 </div>


</body>
</html>